name: nextcloud
version: 2.0.0
description: A Nextcloud client for dart which can use several official Nextcloud APIs
homepage: https://github.com/viktoriaschule/dart-nextcloud

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  xml: ">=4.0.0 <5.0.0"
  intl: ">=0.16.0 <0.17.0"
  http:  ">=0.12.0 <0.13.0"
  crypto: ">=2.0.0 <3.0.0"
  crypton: ">=1.1.0 <2.0.0"

dev_dependencies:
  test: ">=1.0.0 <2.0.0"
  browser_launcher: ">=0.1.0 <0.2.0"
